### ISSUE TITLE
PulseEffects icon has black square underneath

### ISSUE THREAD

**Issue by saidbakr** [L4ki/Amy-Plasma-Themes#2]
I use Amy-Light-Icons set. Almost all icons are fine but the icon of  PulseEffects rendered with an extra black square underneath like shown in the following screen shots:
![image](https://github.com/L4ki/Amy-Plasma-Themes/assets/467554/b948bd3d-2e80-4a88-92cd-55cc3063cee6)

![image](https://github.com/L4ki/Amy-Plasma-Themes/assets/467554/7aadc7b6-1180-4fd0-af1d-c2683ea5aa5d)

![image](https://github.com/L4ki/Amy-Plasma-Themes/assets/467554/15e8f6fc-82fa-40d1-b03d-8fc4468be1fd)

**Comment by L4ki** [comment]
Hi  Said,

The "pulseeffects" icon does not exist in the Amy-Light-Icons. This icon on the screenshot is a default icon when you download the application.

I will now update the "Amy-Light-Icons" icons and add the pulseeeffects icon.

This icon will look like this:


![pulseeffects](https://github.com/L4ki/Amy-Plasma-Themes/assets/45247573/0c792e51-a630-4107-b03a-00fc43900fe6)


I would ask you to check if the icon is in operation.

I don't use that program so I can't check.

P.S.
Greetings to Egypt, I spent two wonderful holidays (summer) in Hurgada.

**Comment by saidbakr** [comment]
Hi L4ki,
The updated icon works fine. However, it need change the icon set to any other set and reset it back to work fine, specially, in Latte dock.
I am proud to see your opinion about Egypt. You always welcomed!

![image](https://github.com/L4ki/Amy-Plasma-Themes/assets/467554/b84b4622-5536-438d-a2fb-d216282ccf85)

![image](https://github.com/L4ki/Amy-Plasma-Themes/assets/467554/08d1cc49-972d-4513-b812-079a522be503)

![image](https://github.com/L4ki/Amy-Plasma-Themes/assets/467554/eec4923e-4376-4847-b64c-11ca0ff64fc2)
