### ISSUE TITLE
Amy Icons causes Firefox crash when opening file pickers by specifying non-existent directories in index.theme

### ISSUE THREAD

**Issue by unit-of-inductance** [L4ki/Amy-Plasma-Themes#6]
When opening a file picker on any Firefox-derived browser and using Amy-Light-Icons, the browser will crash. Logs show that it looks for icons in the directory `~/.local/share/icons/Amy-Light-Icons/status/16@3x/`. I think the main issue is that this directory is listed in the `index.theme` file even though these scaled versions do not exist for this theme.

**Comment by L4ki** [comment]
Hi r0uv3n,

I will add folders with icons: status/16@2x and 16@3x

I would ask you to explain to me how to reach the crash of Firefox, it is not clear to me with "File Picker". That is, what should I do to happen to a demolition?

Greeting,

**Comment by unit-of-inductance** [comment]
> I would ask you to explain to me how to reach the crash of Firefox, it is not clear to me with "File Picker". That is, what should I do to happen to a demolition?

Using e.g. CTRL+O, or Ctrl+S, or saving a PDF, all open a file picker (or save location picker). It seems this crashes Firefox when it can't find the right icons for drives etc., though I don't know which exact icon is the problem here.

**Comment by L4ki** [comment]
Hi r0uv3n,

Thank you for the explanation. I just did it (Ctrl + O, or Ctrl + S, or Saving a PDF), and everything is fine (no demolition 
Firefox), screenshot: [Screenshot-20241103-104922.png](https://postimg.cc/LY2TCKFK)

Did you update the "Amy-Light-Icons" icons I did yesterday?
I recommend uninstalling them, then reinstall.

**Comment by unit-of-inductance** [comment]
Ah yes sorry, everything seems to be fixed!
